[tool.poetry]
name = "cryptodataset"
version = "0.3.8"
description = ""
authors = ["なるみ"]

[tool.poetry.dependencies]
python = "^3.8"
ccxt = "^1.90.10"
pandas = "^1.4.3"
loguru = "^0.6.0"
click = "^8.1.3"
gym = "<0.25.0"
quantstats = "^0.0.59"
pandas-ta = "^0.3.14b0"
jupyter = "^1.0.0"

[tool.poetry.group.dev.dependencies]
yapf = "^0.32.0"
toml = "^0.10.2"
pytest = "^7.1.2"
isort = "^5.10.1"
flake8 = "^4.0.1"

[tool.poetry.scripts]
cryptodataset = "cryptodataset.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
