[tool.poetry]
name = "cryptodataset"
version = "0.3.9"
description = ""
authors = ["なるみ"]

[tool.poetry.dependencies]
python = "^3.8"
ccxt = "^1.90.10"
pandas = "^1.4.3"
loguru = "^0.6.0"
click = "^8.1.3"
pydantic = "^2.4.2"

[tool.poetry.group.dev.dependencies]
toml = "^0.10.2"
pytest = "^7.1.2"
isort = "^5.10.1"
flake8 = "^4.0.1"
black = "^23.9.1"

[tool.poetry.scripts]
cryptodataset = "cryptodataset.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
