name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install .
          kline ccxt -e bitopro -s BTC/TWD -s ETH/TWD -t 1m
