name: Python

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.8", "3.9"]
        poetry-version: ["1.7.1"]

    steps:
      - uses: actions/checkout@v4

      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Test
        run: poetry run pytest --cov=cryptodataset tests
