name: Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.8", "3.9"]
        poetry-version: ["1.8.3"]
    steps:
      - 
        uses: actions/checkout@v4
      - 
        name: Install Poetry
        run: pipx install poetry==${{ matrix.poetry-version }}
      - 
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - 
        name: Install dependencies
        run: poetry install
      - 
        name: Lint
        run: poetry run ruff check .
      - 
        name: Test
        run: poetry run pytest --cov=kline tests
